# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "testd"
version = "0.0.1"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Test Daemon"
homepage = "https://github.com/nanvix"


[[bin]]
name = "testd"


[dependencies]
nvx = { path = "../../nvx" }
