# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true

[profile.dev]
opt-level = 'z'
lto = true
